# ArgoCD install
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
# This is a shortened install; for full, refer to the official docs
# https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# or use Helm
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-server
  namespace: argocd
---
# Example: Add Application manifest if needed
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-username/flask-app-ci'
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
