name: CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'       # Only trigger on changes to helm charts, for example
      - 'k8s/**'        # or Kubernetes manifests folder
      - '.github/workflows/ci-cd.yaml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CD repo
        uses: actions/checkout@v3

      - name: Configure kubectl
        run: |
          # setup kubectl here, e.g.:
          # echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          # or use setup-kubectl action

      - name: Update Helm image tag
        run: |
          sed -i 's/tag:.*/tag: dev-latest/' helm/flask-app/values.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add helm/flask-app/values.yaml
          git commit -m "Update image tag to dev-latest"
          git push

      - name: Deploy with Helm
        run: |
          helm upgrade --install flask-app ./helm/flask-app --namespace default
