name: Build and Deploy Flask App

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - ".github/workflows/ci-cd.yaml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t asaf9879/flask-app:dev-latest ./app

      - name: Push Docker image
        run: docker push asaf9879/flask-app:dev-latest

      - name: Update Helm values.yaml image tag
        run: |
          sed -i 's/tag:.*/tag: dev-latest/' helm/flask-app/values.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add helm/flask-app/values.yaml
          git commit -m "Update image tag to dev-latest"
          git push
