name: CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'
      - 'k8s/**'
      - '.github/workflows/ci-cd.yaml'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CD repo
        uses: actions/checkout@v3

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy with Helm
        run: |
          helm upgrade --install flask-app ./helm/flask-app --namespace default
